# Generated by Django 4.1 on 2022-08-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0002_factory_remove_inventory_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_Img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
