# Generated by Django 4.1 on 2022-08-12 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0003_inventory_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='factory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_control.factory'),
            preserve_default=False,
        ),
    ]
