# Generated by Django 4.1 on 2022-08-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0007_alter_inventory_factory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_Img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
