# Generated by Django 4.1 on 2022-08-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0008_inventory_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
